### ISSUE TITLE
注意安全

### ISSUE THREAD

**Issue by Tomahawkd** [nullptrjzz/sdoj#1]
请不要把密码放上来
https://github.com/nullptrjzz/sdoj/blob/3d208c418a3f7ca98c8119fd8a73982a497ebaf0/src/main/resources/application.yml#L8

**Comment by nullptrjzz** [comment]
这个问题不大，这台机已经不在了🌚以后会注意的


 
---原始邮件---
发件人: "Tomahawkd"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 晚上6:49
收件人: "nullptrjzz/sdoj"<sdoj@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [nullptrjzz/sdoj] 注意安全 (#1)



请不要把密码放上来
 https://github.com/nullptrjzz/sdoj/blob/3d208c418a3f7ca98c8119fd8a73982a497ebaf0/src/main/resources/application.yml#L8
